### ISSUE TITLE
Swift 3 version

### ISSUE THREAD

**Issue by CarsonC01** [hsusmita/GrowingTextViewHandler#4]
Hi do you have a version updated for swift 3?
Thanks

**Comment by anfriis** [comment]
Possible pull request:
https://github.com/hsusmita/GrowingTextViewHandler/pull/3

**Comment by hsusmita** [comment]
@CarsonC01 You can check version 1.1.

**Comment by hsusmita** [comment]
@Anders123fr Thank you for the PR.
